# Generated by Django 4.0.6 on 2022-08-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_notification_notifications_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Receipts',
            new_name='Receipt',
        ),
    ]
